//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public byte Id { get; set; }
        public Nullable<int> SeansId { get; set; }
        public Nullable<int> SeatId { get; set; }
    
        public virtual Sean Sean { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
