//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public byte Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<byte> UserTypeId { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
